apiVersion: v1
kind: Secret
metadata:
  name: violin-calendar-secret
  namespace: violin-dev
  labels:
    app.kubernetes.io/name: violin-calendar
    app.kubernetes.io/component: secret
    environment: dev
type: Opaque
stringData:
  DB_PASSWORD: "CHANGE_ME_DEV_POSTGRES_PASSWORD"
  VIOLIN_JWT_SECRET: "CHANGE_ME_DEV_JWT_SECRET_MIN_32_BYTES"
  REDIS_PASSWORD: "CHANGE_ME_DEV_REDIS_PASSWORD"