CREATE TABLE IF NOT EXISTS CALENDAR_EVENT(
     EVENT_ID INT NOT NULL AUTO_INCREMENT,
     EVENT_DATE CHAR(10),
     TITLE VARCHAR(255),
     EVENT_INFO VARCHAR(255),
     TENANT_ID VARCHAR(255),
     PRIMARY KEY (EVENT_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;